export const GET_ACCIDENTS = "GET_ACCIDENTS";
export const FETCH_ACCIDENTS_ERROR = "FETCH_ACCIDENTS_ERROR";
export const UPDATE_ACCIDENT = "UPDATE_ACCIDENT";
export const UPDATE_ACCIDENT_ERROR = "UPDATE_ACCIDENT_ERROR";
export const LISTENING_ACCIDENT_UPDATE = "LISTENING_ACCIDENT_UPDATE";
export const LISTENED_ACCIDENT_UPDATE = "LISTENED_ACCIDENT_UPDATE";
export const LISTEN_ACCIDENT_UPDATE_ERROR = "LISTEN_ACCIDENT_UPDATE_ERROR";
export const ACCIDENTS_LOADING = "ACCIDENTS_LOADING";

export const GET_USERS = "GET_USERS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const USERS_LOADING = "USERS_LOADING";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_AMBULANCES = "GET_AMBULANCES";
export const FETCH_AMBULANCES_ERROR = "FETCH_AMBULANCES_ERROR";
export const UPDATE_AMBULANCE = "UPDATE_AMBULANCE";
export const UPDATE_AMBULANCE_ERROR = "UPDATE_AMBULANCE_ERROR";
export const AMBULANCES_LOADING = "AMBULANCES_LOADING";
