export const GET_ACCIDENTS = "GET_ACCIDENTS";
export const UPDATE_ACCIDENT = "UPDATE_ACCIDENT";
export const UPDATE_ACCIDENT_ERROR = "UPDATE_ACCIDENT_ERROR";
export const ACCIDENTS_LOADING = "ACCIDENTS_LOADING";

export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";

export const GET_AMBULANCES = "GET_AMBULANCES";
export const UPDATE_AMBULANCE = "UPDATE_AMBULANCE";
export const UPDATE_AMBULANCE_ERROR = "UPDATE_AMBULANCE_ERROR";
export const AMBULANCES_LOADING = "AMBULANCES_LOADING";
