export const GET_ACCIDENTS = "GET_ACCIDENTS";
export const UPDATE_ACCIDENT = "UPDATE_ACCIDENT";
export const ACCIDENTS_LOADING = "ACCIDENTS_LOADING";

export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";

export const GET_AMBULANCES = "GET_AMBULANCES";
export const AMBULANCES_LOADING = "AMBULANCES_LOADING";
